library(readr)
birthwt <- read_csv("~/Desktop/ucsc/birthwt.csv")
View(birthwt)
names(birthwt)
attach(birthwt)
unj.model <- lm(bwt ~ smoke)
summary(unj.model)
confint(unj.model, level = .95)
names(birthwt)
fit.age <- lm(bwt ~ age)
summary(fit.age)
fit.lwt <- lm(bwt ~ lwt)
fit.race <- lm(bwt ~ race)
fit.ptl <- lm(bwt ~ ptl)
fit.ht <- lm(bwt ~ ht)
fit.ui <- lm(bwt ~ ui)
fit.ftv <- lm(bwt ~ ftv)
summary(fit.lwt)
summary(fit.race)
summary(fit.ptl)
summary(fit.ht)
summary(fit.ui)
summary(fit.ftv)
adj.model <- lm(bwt ~ smoke + lwt + ptl + ht + ui)
summary(adj.model)
confint(adj.model, level = .95)
                                                                                                                                                                                                                                
