---
title: "Does Improving Diversity Among Police Officers Reduce Racial Profiling"
output:
  word_document: default
  html_document: default
date: "November 16th, 2017"
names: "Daniel Meza, Mathematics Department, California State Monterey Bay
Adolfo Huerta, Mathematics Department, California State Monterey Bay"
---


### Revisions on Part I
On August of 2014, an African American male, Michael Brown at only eighteen years of age was killed by a police officer after Brown was accused of strong-arm robbing a convenience store. Michael Brown was confirmed as being unarmed, but was still fatally shot after the officer claimed that Brown had allegedly attacked him in order to try and take control of his firearm, until it was fired. However, the officer shot a total of twelve rounds in the whole altercation and at the time he was the only witness. The officer that shot Brown was not charged with murder and was released after the U.S. Department of Justice concluded that the officer shot Brown in self defense (New York Times, 2017). Also, there have been many cases where police officers are accused of racially profiling African Americans, Hispanic and other minorities. The incident that motivated us to take on this topic were the killing of four Hispanic males in Salinas, CA by police in only the span of five months, in the year of 2014. One of our main interests is to identify any type of unfairness between the police officers and minorities. According to Nancy Krieger, a professor of social epidemiology at Harvard T.H. Chan School of Public Health, "Black men, compared to white men, were from five to 19 times at greater risk of a law enforcement-related death over the past 50 years". There is a significant disparity in the risk of death when comparing a minority and a white individual, giving us some evidence to why such topic is important and analyze this issue with our own statistical knowledge. The data we will analyze does not contain information about people getting killed by police. We will only try to provide evidence to issues regarding racial profiling from traffic stop information. Therefore, the first question we want to analyze is if police officers regardless of ethnicity target more Hispanics over whites. In the study, "Black and Hispanic Men Perceived to Be Large Are at Increased Risk for Police Frisk, Search, and Force" they look at a similar scenario where the results showed that indeed Black and Hispanic suspects were at a greater risk of being frisked or searched compared to whites. Next, we want to determine if the result of the stop for a minority is less severe on average when the police officer is a minority.  In recent years, research explains that about six percent more of the stops were between a white officer and black citizen over a white officer and white citizen being stopped(Criminology, 2012). Finally, we would like to see the results of being stopped leading to being searched is higher for African Americans and Hispanics than for white citizens. In a 2011 report, the Leadership Conference on Civil Rights found evidence of widespread racial profiling, showing that African Americans and Hispanics are disproportionately likely to be stopped and searched by police, even though they're less likely to be found possessing contraband or committing a criminal act. For example, in Illinois, Hispanic and black drivers were twice as likely to be searched after being stopped by police compared to white drivers, but the surprising thing was that white drivers were twice as likely to have contraband in their possession (Washington Post, 2014).
###Partial Methods

The traffic stop data was downloaded from Data.Gov. The Records from all 79885 reported traffic stops was for a large Southeastern city in 2016. There is no information on how the data was collected. For all of our questions we will use multinomial regression or logistic regression.
The variables are defined in the following way:
Variables/Names Month 1-12 (Month)
Reason for Stop (RsnStop)
Officer Race (OffRace)
Officer Male (OffMale)
Officer Years Service (OffYrsSrv)
Driver Race (DrvRace)
Driver Hispanic (DrvHisp)
Driver Male (DrvMale)
Driver Age (DrvAge)
Search Vehicle (SrchVhcl)
Result of Stop (RsltStop)
Levels for categorical variables
Reason for Stop: 1=CheckPoint, 2=DWI, 3=Investigation, 4=Other, 5=Safe Movement, 6=SeatBelt, 7=Speeding, 8=StopLight/Sign, 9=VehicleMovement, 10=VehicleRegistry
Officer race: Blank=NotSpecified, 1=AmericanIndian/NativeAlaska/Hawaii, 2=Asian/PacificIslander, 3=Black/AfricanAmerican, 4=Hispanic/Latino, 5=White
Driver Race: 1=Asian, 2=Black, 3=NativeAmerican,4=Other/Unknown,5=White
Result of Stop: 1=NoActionTaken, 2=VerbalWarning,3=WrittenWarning, 4=Citation, 5=Arrest
Note that the echo = FALSE parameter was added to the code chunk to prevent printing of the R code that generated the plot.
###Partial results

In the traffic stop data set from a large southeastern city of the United States, we found that the mean age of the drivers was about 36 years old. Also, we could observe that the mean number of service years for the police officers in this data set was around 11 years. As we continued to explore the data we found that the proportion of drivers who are males is about 58 percent while the percent of female drivers was about 42 percent.  Our first question focuses on if Hispanics are targeted more than whites regardless of the gender of the police officer.  In the data set there are 7578 drivers who were identified as Hispanics. We now explored more specific summary statistics for each question. Our first question is about observing how severe is the result of a stop for a driver who is a minority when the police officer is also a minority. Since our variables are mostly categorical we decided to create tables. According to Figure 1A in the appendix, we can observe a table with crucial information about a drivers race and a police officers race. For example, the total number of times that an Asian driver got stopped by a white officer is 1072 times. On the other hand, when the driver was black we can observe that the number of times stopped by a white officer actually is drastically larger with 30993 traffic stops. Another great representation of the data was through a proportions table where we can observe the proportion of traffic stop by an officer's race and the drivers race.
Our second question focuses on if Hispanics are targeted more than whites regardless of the gender of the police officer.  In the data set there are 7578 drivers who were identified as Hispanic.  In figure 2a, the table summarizes the distribution of Hispanics among the rest of the ethnicities. Now from this information we observe that 5305 traffic stops happened when the driver was Hispanic and the officer was white. The proportion of Hispanic drivers stopped by the different officer race's can be observed in figure 2b.We also conducted a multinomial regression model for each of the first two questions and the results for the models will be interpreted in the next part of the project.
For our third part of the project, we would like to see the results of being stopped leading to being searched is
higher for minorities like African Americans and Hispanics than for other citizens like whites?  For our summary statistics we compare the result of being stopped versus the binary outcome of being searched or not in a table.  Then we also compare the binary event of being searched versus the drivers race and calculate the proportions.  The proportions are as follows asian drivers that were searched was 0.0116, black drivers that were searched was 0.0576, native american drivers that were searched was 0.0322, and white drivers that were searched was 0.0206.  Not suprisingly, we see that the proportion of black drivers being searched was the highest and the lowest proportions searched were when the drivers were asian and white, respectively. However, this is only from this sample and we need more test to see if there is a statistically significant difference between these races. We also conducted a simple logistic regression model with a vehicle being searched being the qualitative response variable and the drivers race being the qualitative response variable.  We find that without adjusting for confounding variables, that the races asian, black and white are statistically significant predictors of the response, but the race titled as other/unknown is not statistically significant predictor.  In the next part we will adjust this model to include the explanatory variables we believe could have predictive power over our response like Reason for Stop, Officers Race, Officer Male, Officer Years Service, Driver Male and the Drivers Age.

###Partial Appendix
General Summary Statistics
```{r}
library(readr)
trafficstop <- read_csv("~/Desktop/ucsc/trafficstop.csv")

attach(trafficstop)
mean(DrvAge)
mean(OffYrsSrv)
men<-sum(DrvMale==1)
men_prop<-men/length(DrvAge)
men_prop
women<-sum(DrvMale==0)
women_prop<-women/length(DrvAge)
########### summary Statistics  question 1

#install.packages("expss")
#install.packages("matrixStats")
library(expss)
library(matrixStats)
trafficstop1 = apply_labels(trafficstop,
                      OffRace = "Officers Race",
                      OffRace = c("American Indian/Native Alaska/Hawaii" = 1,
                             "Asian/Pacific Islander" = 2
                             ,"Black/African American"=3,"Hispanic/Latino"=4,"White"=5
                             
                             
                             
                             ),
                      DrvRace = "Drivers Race",
                      DrvRace = c("Asian" = 1,
                                  "Black"=2,
                                  "Native American"=3,
                                  "Other"=4,
                                  "White"=5
                                  
                                  )
                      
)
#Figure 1A
#cro(trafficstop1$DrvRace,trafficstop1$OffRace)###### Frequency table for first question


#Figure 1B
#cro_cpct(trafficstop1$OffRace, list(total(), trafficstop1$DrvRace))### proportions



########################### Summary Stats for question 2

#Based on that we know that Hispanics are a minority in the United States, we will take the lowest sum of the categorical variable DrvHispanic and define it as Hispanic. 
sum(trafficstop$DrvHisp==1)

sum(trafficstop$DrvHisp==2)
### Now we have some certainty that the categorical value 1 of the variable DrvHispanic is for the drivers who were hispanic. 



trafficstop2 = apply_labels(trafficstop,
                            OffRace = "Officers Race",
                            OffRace = c("American Indian/Native Alaska/Hawaii" = 1,
                                        "Asian/Pacific Islander" = 2
                                        ,"Black/African American"=3,"Hispanic/Latino"=4,"White"=5
                                        
                                        
                                        
                            ),
                            DrvHisp = "Hispanic Drivers",
                            DrvHisp = c("Hispanic" = 1,
                                        "Other"=2
                                        
                            )
                            
)
#cro(trafficstop2$DrvHisp,trafficstop2$OffRace)###### Frequency table for Second question


#cro_cpct(trafficstop2$OffRace, list(total(), trafficstop2$DrvHisp))### proportions

########################### Summary Stats for question 3


#Comparing the results of the stop versus if the person got searched
table(SrchVhcl, factor(RsltStop))
#Comparing the drivers race versus if the person got searched
table(SrchVhcl, factor(DrvRace))
#Calculate what proportions of drivers got searched for each race
prop.asian.searched <- 17 / (1444 + 17)
prop.asian.searched
prop.black.searched <- 2478 / (2478 + 40492)
prop.black.searched
prop.native.searched <- 2 / 62
prop.native.searched
prop.other.searched <- 33 / ( 33 + 2389)
prop.white.searched <- 678 / (678 + 32291)
prop.white.searched








############################# Modeling question 1
library(readr)
#install.packages("VGAM")
library(VGAM)
offrace <- factor(trafficstop$OffRace)
contrasts(offrace)=contr.treatment(levels(offrace),base=5)
contrasts(offrace)
q_Hispanic<-vglm((factor(DrvHisp)~factor(offrace)),data=trafficstop,family = multinomial())
summary(q_Hispanic)

############################ Modeling Question 2
library(readr)
#install.packages("VGAM")
library(VGAM)

#Alana's code
offrace <- factor(trafficstop$OffRace)
contrasts(offrace)=contr.treatment(levels(offrace),base=5)
contrasts(offrace)
q12<-vglm((factor(RsltStop)~factor(offrace)),data=trafficstop,family = multinomial())
summary(q12)
#### Addding Service years to the model to make it more significant
q13<-vglm((factor(RsltStop)~factor(offrace)+OffYrsSrv),data=trafficstop,family = multinomial())
summary(q13)

############################ Modeling Question 3

## Create reduced model, simple logistic binomial, to test wheter Drivers Race has significant predictive power over the response Search Vehicle.
SearchRaceModel <- glm(SrchVhcl ~ factor(DrvRace), family = "binomial")
summary(SearchRaceModel)